Linting:
  runs-on: ubuntu-latest
  needs: [Build]
  steps:
    - name: Download repo
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: run linting
      uses: super-linter/super-linter/slim@v5
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
