# This is a basic workflow to help you get started with Actions

Linting:
  runs-on: ubuntu-latest
  needs: [Build]
  steps:
    - name: Download repo
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: Super-linter
      uses: super-linter/super-linter/slim@v6.8.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
